db.username=itsa
db.password=itsa123
db.name=hwlogger
db.port=3306
db.unit7.address=10.0.1.230
db.unit9.address=192.168.100.230
db.local.address=localhost

#Time in seconds
db.timeout=1

db.autoReconnect=true
db.maxReconnects=3
db.useLocalhost=true
db.localhost.username=root
db.localhost.password=root